<a href="https://colab.research.google.com/github/Olacherish/DataScienceClass/blob/main/AI_DATASETS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**BUILDING A ML MODEL USING SKLEARN**

In [ ]:
import sklearn

In [ ]:
# from sklearn.linear_models.LogisticRegression
from sklearn.linear_model import LinearRegression # model
from sklearn.datasets import load_breast_cancer # datasets
data = load_breast_cancer(as_frame=True)
from sklearn import train_test_split
from sklearn import\
(   accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    root_mean_squared_error,
    mean_squared_error,
    f1_score,

  )
import numpy as np

data.data

In [ ]:
print(dir(sklearn))

['calibration', 'clone', 'cluster', 'compose', 'config_context', 'covariance', 'cross_decomposition', 'datasets', 'decomposition', 'discriminant_analysis', 'dummy', 'ensemble', 'exceptions', 'experimental', 'externals', 'feature_extraction', 'feature_selection', 'frozen', 'gaussian_process', 'get_config', 'impute', 'inspection', 'isotonic', 'kernel_approximation', 'kernel_ridge', 'linear_model', 'manifold', 'metrics', 'mixture', 'model_selection', 'multiclass', 'multioutput', 'naive_bayes', 'neighbors', 'neural_network', 'pipeline', 'preprocessing', 'random_projection', 'semi_supervised', 'set_config', 'show_versions', 'svm', 'tree']

In [ ]:
from sklearn import linear_model

In [ ]:
from sklearn import linear_model
print(dir(linear_model))

['ARDRegression', 'BayesianRidge', 'ElasticNet', 'ElasticNetCV', 'GammaRegressor', 'HuberRegressor', 'Lars', 'LarsCV', 'Lasso', 'LassoCV', 'LassoLars', 'LassoLarsCV', 'LassoLarsIC', 'LinearRegression', 'LogisticRegression', 'LogisticRegressionCV', 'MultiTaskElasticNet', 'MultiTaskElasticNetCV', 'MultiTaskLasso', 'MultiTaskLassoCV', 'OrthogonalMatchingPursuit', 'OrthogonalMatchingPursuitCV', 'PassiveAggressiveClassifier', 'PassiveAggressiveRegressor', 'Perceptron', 'PoissonRegressor', 'QuantileRegressor', 'RANSACRegressor', 'Ridge', 'RidgeCV', 'RidgeClassifier', 'RidgeClassifierCV', 'SGDClassifier', 'SGDOneClassSVM', 'SGDRegressor', 'TheilSenRegressor', 'TweedieRegressor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_bayes', '_cd_fast', '_coordinate_descent', '_glm', '_huber', '_least_angle', '_linear_loss', '_logistic', '_omp', '_passive_aggressive', '_perceptron', '_quantile', '_ransac', '_ridge', '_sag', '_sag_fast', '_sgd_fast', '_stochastic_gradient', '_theil_sen', 'enet_path', 'lars_path', 'lars_path_gram', 'lasso_path', 'orthogonal_mp', 'orthogonal_mp_gram', 'ridge_regression']

In [ ]:
from sklearn.metrics import(
    mean_squared_error,
    root_mean_squared_error,
    precision_recall_curve,
    recall_score,

In [ ]:
from sklearn import linear_model
from sklearn import metrics
from sklearn import neural_network

**Step 1: Load Datasets**

In [ ]:
# datasets
- Malignant-> 212 examples/datapoints/instances
- Benign -> 357 examples/datapoints/instances

In [ ]:
# from sklearn.linear_models.LogisticRegression

data = load_breast_cancer(as_frame=True)

x = data.data
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
x.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
y = data.target   # y = Label or Target
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

In [ ]:
# from sklearn.linear_models.LogisticRegression
from sklearn.linear_model import LinearRegression # model
from sklearn.datasets import load_breast_cancer # datasets
data = load_breast_cancer(as_frame=True)

data.data

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
print(load_breast_cancer().DESCR)

In [ ]:
from sklearn.metrics import mean_squared_error
import numpy as np

# Sample true values and predicted values for a regression model
y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])

# Calculate Mean Squared Error
mse = mean_squared_error(y_true, y_pred)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.375

## **STEP TWO: SPLITTING THE DATASETS**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer

# Load the dataset and define x (features) and y (target)
data = load_breast_cancer(as_frame=True)
x = data.data
y = data.target

# Split the x, y data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

## **STEP THREE: TRAIN THE MODEL**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Instantiate the Logistic Regression model
# (Assuming logistic_regression_model was defined in a previous cell and is available)
logistic_regression_model = LogisticRegression(max_iter=20000, random_state=42)

# Train the model
logistic_regression_model.fit(x_train, y_train)

# Make predictions on the test set
y_pred = logistic_regression_model.predict(x_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

NameError: name 'x_train' is not defined

### Feature Importance from Model Coefficients

In [ ]:
import pandas as pd

# Get the coefficients from the trained model
coefficients = logistic_regression_model.coef_[0]

# Get the feature names from the training data
feature_names = x_train.columns

# Create a DataFrame to display feature importance
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Coefficient': coefficients
})

# Sort by the absolute value of the coefficients to see the most impactful features
feature_importance_df['Absolute_Coefficient'] = feature_importance_df['Coefficient'].abs()
feature_importance_df = feature_importance_df.sort_values(by='Absolute_Coefficient', ascending=False)

display(feature_importance_df.drop(columns=['Absolute_Coefficient']))

AttributeError: 'LogisticRegression' object has no attribute 'coef_'

In [ ]:
# Split the datasets
1) Train set
2) Test set
train_test_split()

In [ ]:
# from sklearn.linear_models.LogisticRegression
from sklearn.linear_model import LinearRegression # model
from sklearn.datasets import load_breast_cancer # datasets
from sklearn.model_selection import train_test_split
data = load_breast_cancer(as_frame=True)

x = data.data
x

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
x.shape

(569, 30)

In [ ]:
569*0.30

170.7

In [ ]:
x.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
dtype: object

In [ ]:
train_test_split(x, test_size=0.30)

[     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
 29         17.57         15.05          115.00      955.1          0.09847
 108        22.27         19.67          152.80     1509.0          0.13260
 536        14.27         22.55           93.77      629.8          0.10380
 217        10.20         17.48           65.05      321.2          0.08054
 410        11.36         17.57           72.49      399.8          0.08858
 ..           ...           ...             ...        ...              ...
 3          11.42         20.38           77.58      386.1          0.14250
 382        12.05         22.72           78.75      447.8          0.06935
 122        24.25         20.20          166.20     1761.0          0.14470
 268        12.87         16.21           82.38      512.2          0.09425
 41         10.95         21.35           71.90      371.1          0.12270

      mean compactness  mean concavity  mean concave points  mean symmetry  \
 29            0.11570         0.09875              0.07953         0.1739
 108           0.27680         0.42640              0.18230         0.2556
 536           0.11540         0.14630              0.06139         0.1926
 217           0.05907         0.05774              0.01071         0.1964
 410           0.05313         0.02783              0.02100         0.1601
 ..                ...             ...                  ...            ...
 3             0.28390         0.24140              0.10520         0.2597
 382           0.10730         0.07943              0.02978         0.1203
 122           0.28670         0.42680              0.20120         0.2655
 268           0.06219         0.03900              0.01615         0.2010
 41            0.12180         0.10440              0.05669         0.1895

      mean fractal dimension  ...  worst radius  worst texture  \
 29                  0.06149  ...         20.01          19.52
 108                 0.07039  ...         28.40          28.01
 536                 0.05982  ...         15.29          34.27
 217                 0.06315  ...         11.48          24.47
 410                 0.05913  ...         13.05          36.32
 ..                      ...  ...           ...            ...
 3                   0.09744  ...         14.91          26.50
 382                 0.06659  ...         12.57          28.71
 122                 0.06877  ...         26.02          23.99
 268                 0.05769  ...         13.90          23.64
 41                  0.06870  ...         12.84          35.34

      worst perimeter  worst area  worst smoothness  worst compactness  \
 29            134.90      1227.0           0.12550             0.2812
 108           206.80      2360.0           0.17010             0.6997
 536           104.30       728.3           0.13800             0.2733
 217            75.40       403.7           0.09527             0.1397
 410            85.07       521.3           0.14530             0.1622
 ..               ...         ...               ...                ...
 3              98.87       567.7           0.20980             0.8663
 382            87.36       488.4           0.08799             0.3214
 122           180.90      2073.0           0.16960             0.4244
 268            89.27       597.5           0.12560             0.1808
 41             87.22       514.0           0.19090             0.2698

      worst concavity  worst concave points  worst symmetry  \
 29            0.2489               0.14560          0.2756
 108           0.9608               0.29100          0.4055
 536           0.4234               0.13620          0.2698
 217           0.1925               0.03571          0.2868
 410           0.1811               0.08698          0.2973
 ..               ...                   ...             ...
 3             0.6869               0.25750          0.6638
 382           0.2912               0.10920          0.2191
 122           0.5803               0.22480          0.3222
 268           0.1992               0.05780          0.3604
 41            0.4023               0.14240          0.2964

      worst fractal dimension
 29                   0.07919
 108                  0.09789
 536                  0.08351
 217                  0.07809
 410                  0.07745
 ..                       ...
 3                    0.17300
 382                  0.09349
 122                  0.08009
 268                  0.07062
 41                   0.09606

 [398 rows x 30 columns],
      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
 450        11.87         21.54           76.83      432.0          0.06613
 383        12.39         17.48           80.64      462.9          0.10420
 264        17.19         22.07          111.60      928.3          0.09726
 307         9.00         14.40           56.36      246.3          0.07005
 266        10.60         18.95           69.28      346.4          0.09688
 ..           ...           ...             ...        ...              ...
 263        15.61         19.38          100.00      758.6          0.07840
 50         11.76         21.60           74.72      427.9          0.08637
 282        19.40         18.18          127.20     1145.0          0.10370
 1          20.57         17.77          132.90     1326.0          0.08474
 402        12.96         18.29           84.18      525.2          0.07351

      mean compactness  mean concavity  mean concave points  mean symmetry  \
 450           0.10640        0.087770             0.023860         0.1349
 383           0.12970        0.058920             0.028800         0.1779
 264           0.08995        0.090610             0.065270         0.1867
 307           0.03116        0.003681             0.003472         0.1788
 266           0.11470        0.063870             0.026420         0.1922
 ..                ...             ...                  ...            ...
 263           0.05616        0.042090             0.028470         0.1547
 50            0.04966        0.016570             0.011150         0.1495
 282           0.14420        0.162600             0.094640         0.1893
 1             0.07864        0.086900             0.070170         0.1812
 402           0.07899        0.040570             0.018830         0.1874

      mean fractal dimension  ...  worst radius  worst texture  \
 450                 0.06612  ...        12.790          28.18
 383                 0.06588  ...        14.180          23.13
 264                 0.05580  ...        21.580          29.33
 307                 0.06833  ...         9.699          20.07
 266                 0.06491  ...        11.880          22.94
 ..                      ...  ...           ...            ...
 263                 0.05443  ...        17.910          31.67
 50                  0.05888  ...        12.980          25.72
 282                 0.05892  ...        23.790          28.65
 1                   0.05667  ...        24.990          23.41
 402                 0.05899  ...        14.130          24.61

      worst perimeter  worst area  worst smoothness  worst compactness  \
 450            83.51       507.2           0.09457            0.33990
 383            95.23       600.5           0.14270            0.35930
 264           140.50      1436.0           0.15580            0.25670
 307            60.90       285.5           0.09861            0.05232
 266            78.28       424.8           0.12130            0.25150
 ..               ...         ...               ...                ...
 263           115.90       988.6           0.10840            0.18070
 50             82.98       516.5           0.10850            0.08615
 282           152.40      1628.0           0.15180            0.37490
 1             158.80      1956.0           0.12380            0.18660
 402            96.31       621.9           0.09329            0.23180

      worst concavity  worst concave points  worst symmetry  \
 450          0.32180               0.08750          0.2305
 383          0.32060               0.09804          0.2819
 264          0.38890               0.19840          0.3216
 307          0.01472               0.01389          0.2991
 266          0.19160               0.07926          0.2940
 ..               ...                   ...             ...
 263          0.22600               0.08568          0.2683
 50           0.05523               0.03715          0.2433
 282          0.43160               0.22520          0.3590
 1            0.24160               0.18600          0.2750
 402          0.16040               0.06608          0.3207

      worst fractal dimension
 450                  0.09952
 383                  0.11180
 264                  0.07570
 307                  0.07804
 266                  0.07587
 ..                       ...
 263                  0.06829
 50                   0.06563
 282                  0.07787
 1                    0.08902
 402                  0.07247

 [171 rows x 30 columns]]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [ ]:
# Split the x data
x_train, x_test = train_test_split(x, test_size=0.30, random_state=26)

# Split the label
y_train, y_test = train_test_split(y, test_size=0.30, random_state=26)

#Split the x, y data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=26)

In [ ]:
x_train and y_train -> train the model # Training set
x_test and y_test -> Evaluate the model # Testing set

## **STEP 3: TRAINING THE MODEL**

In [ ]:
from sklearn.linear_model import LogisticRegression, LinearRegression # Import both classes

# Instantiate the Logistic Regression model
logistic_regression_model = LogisticRegression(max_iter=20000) # Increased max_iter for convergence

# Instantiate the Linear Regression model (if needed later)
linear_regression_model = LinearRegression()

In [ ]:
log_model = logistic_regression.fit(x_train, y_train)
lin_model = linear_regression.fit(x_train, y_train)

In [ ]:
# training our logistics regression model
# x_train, y_train are variables
# train the Logistic Regression model using the correctly instantiated object
logistic_regression_model.fit(x_train, y_train)
LogisticRegression(max_iter=20000, random_state=42)
log_model.fit(x_train, y_train)

LogisticRegression(max_iter=20000, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# Load the dataset
data = load_breast_cancer(as_frame=True)
x = data.data
y = data.target

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

# Instantiate the Logistic Regression model
# It's good practice to set a random_state for reproducibility
logistic_regression_model = LogisticRegression(max_iter=20000, random_state=42)

# training our logistics regression model
# train the Logistic Regression model using the correctly instantiated object
log_model = logistic_regression_model.fit(x_train, y_train)

In [ ]:
# Instantiate the Logistic Regression model
logistic_regression_model = log_model.fit(x_train, y_train)

# training our logistics regression model
# x_train, y_train are variables
x_train, y_train

# train the Logistic Regression model using the correctly instantiated object
logistic_regression_model = LogisticRegression(max_iter=20000) # Increased max_iter for convergence

# log_model = logistic_regression_model.fit(x_train, y_train)
LogisticRegression(max_iter=20000, random_state=42) = log_model.fit(x_train, y_train)

## **EVALUATE THE MODEL**

In [ ]:
example = x_test.iloc[0]
example
x_test.iloc[0]

mean radius                  18.010000
mean texture                 20.560000
mean perimeter              118.400000
mean area                  1007.000000
mean smoothness               0.100100
mean compactness              0.128900
mean concavity                0.117000
mean concave points           0.077620
mean symmetry                 0.211600
mean fractal dimension        0.060770
radius error                  0.754800
texture error                 1.288000
perimeter error               5.353000
area error                   89.740000
smoothness error              0.007997
compactness error             0.027000
concavity error               0.037370
concave points error          0.016480
symmetry error                0.028970
fractal dimension error       0.003996
worst radius                 21.530000
worst texture                26.060000
worst perimeter             143.400000
worst area                 1426.000000
worst smoothness              0.130900
worst compactness             0.232700
worst concavity               0.254400
worst concave points          0.148900
worst symmetry                0.325100
worst fractal dimension       0.076250
Name: 492, dtype: float64

In [ ]:
log_model.predict( x_test)

In [ ]:
y_test = np.array(y_test)

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
import numpy as np
import sklearn
from sklearn.metrics import accuracy_score

# Get predictions from the model
log_model = LogisticRegression(max_iter=20000,
                               random_state=42)
log_model.fit(x_train, y_train)

# Ensure y_pred is a numpy array
y_pred = log_model.predict(x_test)
y_pred = np.array(y_pred)

# Computing the Accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

Model Accuracy: 0.9766

In [ ]:
log_model = LogisticRegression()

In [ ]:
log_model

LogisticRegression(max_iter=20000, random_state=42)

In [ ]:
# create an instance of the class
log_model = LogisticRegression()

In [ ]:
log_model = LogisticRegression(max_iter=20000)

In [ ]:
# training our Logistic regressionnmodel
log_model.fit(x_train, y_train)

LogisticRegression(max_iter=20000)

## **STEP FOUR: EVALUATE THE MODEL**

In [63]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [ ]:
x_test

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
204,12.470,18.60,81.09,481.9,0.09965,0.10580,0.08005,0.03821,0.1925,0.06373,...,14.97,24.64,96.05,677.9,0.1426,0.23780,0.2671,0.10150,0.3014,0.08750
70,18.940,21.31,123.60,1130.0,0.09009,0.10290,0.10800,0.07951,0.1582,0.05461,...,24.86,26.58,165.90,1866.0,0.1193,0.23360,0.2687,0.17890,0.2551,0.06589
131,15.460,19.48,101.70,748.9,0.10920,0.12230,0.14660,0.08087,0.1931,0.05796,...,19.26,26.00,124.90,1156.0,0.1546,0.23940,0.3791,0.15140,0.2837,0.08019
431,12.400,17.68,81.47,467.8,0.10540,0.13160,0.07741,0.02799,0.1811,0.07102,...,12.88,22.91,89.61,515.8,0.1450,0.26290,0.2403,0.07370,0.2556,0.09359
540,11.540,14.44,74.65,402.9,0.09984,0.11200,0.06737,0.02594,0.1818,0.06782,...,12.26,19.68,78.78,457.8,0.1345,0.21180,0.1797,0.06918,0.2329,0.08134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,12.780,16.49,81.37,502.5,0.09831,0.05234,0.03653,0.02864,0.1590,0.05653,...,13.46,19.76,85.67,554.9,0.1296,0.07061,0.1039,0.05882,0.2383,0.06410
542,14.740,25.42,94.70,668.6,0.08275,0.07214,0.04105,0.03027,0.1840,0.05680,...,16.51,32.29,107.40,826.4,0.1060,0.13760,0.1611,0.10950,0.2722,0.06956
176,9.904,18.06,64.60,302.4,0.09699,0.12940,0.13070,0.03716,0.1669,0.08116,...,11.26,24.39,73.07,390.2,0.1301,0.29500,0.3486,0.09910,0.2614,0.11620
501,13.820,24.49,92.33,595.9,0.11620,0.16810,0.13570,0.06759,0.2275,0.07237,...,16.01,32.94,106.00,788.0,0.1794,0.39660,0.3381,0.15210,0.3651,0.11830
247,12.890,14.11,84.95,512.2,0.08760,0.13460,0.13740,0.03980,0.1596,0.06409,...,14.39,17.70,105.00,639.1,0.1254,0.58490,0.7727,0.15610,0.2639,0.11780

In [ ]:
x_test.iloc[0]

mean radius                 12.470000
mean texture                18.600000
mean perimeter              81.090000
mean area                  481.900000
mean smoothness              0.099650
mean compactness             0.105800
mean concavity               0.080050
mean concave points          0.038210
mean symmetry                0.192500
mean fractal dimension       0.063730
radius error                 0.396100
texture error                1.044000
perimeter error              2.497000
area error                  30.290000
smoothness error             0.006953
compactness error            0.019110
concavity error              0.027010
concave points error         0.010370
symmetry error               0.017820
fractal dimension error      0.003586
worst radius                14.970000
worst texture               24.640000
worst perimeter             96.050000
worst area                 677.900000
worst smoothness             0.142600
worst compactness            0.237800
worst concavity              0.267100
worst concave points         0.101500
worst symmetry               0.301400
worst fractal dimension      0.087500
Name: 204, dtype: float64

In [ ]:
log_model.predict(x_test) # y_pred = log_model.predict(x_test)

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [ ]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
y_test

204    1
70     0
131    0
431    1
540    1
      ..
69     1
542    1
176    1
501    0
247    1
Name: target, Length: 171, dtype: int64

In [ ]:
import numpy as np
np.array(y_test) # y_test = np.array(y_test)

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [ ]:
# Computing the Accuracy score of the model
accuracy_score(y_pred, y_test)

0.9766081871345029

In [ ]:
y_test

204    1
70     0
131    0
431    1
540    1
      ..
69     1
542    1
176    1
501    0
247    1
Name: target, Length: 171, dtype: int64

In [ ]:
# computing confusion matrics

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 61,   2],
       [  2, 106]])

In [ ]:
#calculating precision

from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

0.9814814814814815

In [47]:
from sklearn.datasets import load_diabetes

sklearn.datasets._base.load_diabetes
def load_diabetes(return_X_y=False,
                  as_frame=True, scaled=False,
                  n_targets=1):
  load_diabetes

In [48]:
from sklearn.datasets import load_diabetes

sklearn.datasets.load_diabetes
load_diabetes

In [60]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [61]:
y_test

204    1
70     0
131    0
431    1
540    1
      ..
69     1
542    1
176    1
501    0
247    1
Name: target, Length: 171, dtype: int64

In [64]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        63
           1       0.98      0.98      0.98       108

    accuracy                           0.98       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.98      0.98      0.98       171

In [57]:
from sklearn.datasets import load_diabetes

In [59]:
data = load_diabetes(as_frame=True)
x = data.data
y = data.target

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.30, random_state=42)

In [ ]:
# linear_model is also the same as linear_regression_model
linear_regression_model = LinearRegression()

In [ ]:
y_pred = linear_regression_model.predict(x_test)

In [54]:
from sklearn.metrics import root_mean_squared_error

root_mean_squared_error(y_test, y_pred)

0.1529438225803745

In [55]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_pred)

0.023391812865497075